Document: sensorfw
Title: Debian sensorfw Manual
Author: <insert document author here>
Abstract: This manual describes what sensorfw is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sensorfw/sensorfw.sgml.gz

Format: postscript
Files: /usr/share/doc/sensorfw/sensorfw.ps.gz

Format: text
Files: /usr/share/doc/sensorfw/sensorfw.text.gz

Format: HTML
Index: /usr/share/doc/sensorfw/html/index.html
Files: /usr/share/doc/sensorfw/html/*.html
